import { marked } from 'marked'
import { markedEmoji } from 'marked-emoji'

const GITHUB_EMOJI_MAP: Record<string, string> = {
  rocket: '🚀', thumbsup: '👍', thumbsdown: '👎', clap: '👏', tada: '🎉', fire: '🔥',
  star: '⭐', heart: '❤️', eyes: '👀', sparkle: '✨', check: '✅', x: '❌',
  warning: '⚠️', bug: '🐛', hammer: '🔨', wrench: '🔧', tools: '🛠️', gear: '⚙️',
  chart_with_upwards_trend: '📈', bar_chart: '📊', microscope: '🔬', bulb: '💡',
  money_with_wings: '💸', globe_with_meridians: '🌐', laptop: '💻', desktop_computer: '🖥️',
  keyboard: '⌨️', phone: '📱', tv: '📺', radio: '📻',
  camera: '📷', video_camera: '📹', bookmark: '🔖', link: '🔗',
  paperclip: '📎', scissors: '✂️', pencil: '✏️', lock: '🔒', unlock: '🔓',
  key: '🔑', shield: '🛡️', crossed_swords: '⚔️', skull: '💀', ghost: '👻',
  alien: '👽', robot: '🤖', smiley: '😀', smile: '😊', joy: '😂',
  heart_eyes: '😍', kiss: '💋', grin: '😁', sob: '😭',
  angry: '😠', rage: '😡', cry: '😭', wave: '👋', ok_hand: '👌', v: '✌️',
  pray: '🙏', muscle: '💪', brain: '🧠',
  dog: '🐶', cat: '🐱', fox: '🦊', bear: '🐻', panda: '🐼', tiger: '🐯',
  lion: '🦁', cow: '🐮', pig: '🐷', frog: '🐸', monkey: '🐵', chicken: '🐔',
  bird: '🐦', duck: '🦆', eagle: '🦅', owl: '🦉', wolf: '🐺', horse: '🐴',
  unicorn: '🦄', bee: '🐝', butterfly: '🦋', ant: '🐜',
  spider: '🕷️', turtle: '🐢', snake: '🐍', octopus: '🐙', fish: '🐟',
  dolphin: '🐬', whale: '🐳', shark: '🦈', elephant: '🐘', trophy: '🏆',
  medal_sports: '🏅', soccer: '⚽', basketball: '🏀', football: '🏈', tennis: '🎾',
  volleyball: '🏐', golf: '⛳', ski: '🎿', game_die: '🎲',
  joypad: '🎮', chess: '♟️', dart: '🎯', music: '🎵',
  guitar: '🎸', saxophone: '🎷', trumpet: '🎺', drum: '🥁', violin: '🎻',
  microphone: '🎤', headphones: '🎧', musical_note: '🎵', notes: '🎶',
  clown: '🤡', Crown: '👑', woman: '👩', man: '👨', child: '👶', older_adult: '🧓',
  bride_with_veil: '👰', person_in_tuxedo: '🤵', baby_angel: '👼', Santa: '🎅',
  fairy: '🧚', merperson: '🧜', elf: '🧝', vampire: '🧛',
  superhero: '🦸', supervillain: '🦹', zombie: '🧟',
  genie: '🧞', demon: '👹', ogre: '👺', dragon_face: '🐲', dragon: '🐉',
  sparkles: '✨', stars: '🌟', sunny: '☀️', partly_sunny: '⛅', cloud: '☁️',
  cloud_with_rain: '🌧️', thunder_cloud_and_rain: '⛈️', zap: '⚡', droplet: '💧', water_wave: '🌊',
  snowflake: '❄️', snowman: '☃️', umbrella: '☂️',
  hash: '#️⃣', keycap_star: '*️⃣', zero: '0️⃣', one: '1️⃣', two: '2️⃣',
  three: '3️⃣', four: '4️⃣', five: '5️⃣', six: '6️⃣', seven: '7️⃣', eight: '8️⃣',
  nine: '9️⃣', ten: '🔟',1234: '🔢', input_numbers: '🔢', ABC: '🔤',
  input_latin_uppercase: '🔤', input_latin_lowercase: '🔡', input_symbols: '🔣',
  triangular_flag_on_post: '🚩', triangular_ruler: '📐', straight_ruler: '📏',
  file_folder: '📁', open_file_folder: '📂', page_facing_up: '📄', page_with_curl: '📃',
  notebook: '📓', ledger: '📒', clipboard: '📋',
  spiral_calendar: '🗓️', tear_off_calendar: '📆', card_index: '📇',
  pencil2: '✒️', black_nib: '🖋️', fountain_pen: '🖊️', paintbrush: '🖌️', crayon: '🖍️',
  mag: '🔍', mag_right: '🔎', lock_with_ink_pen: '🔏', closed_lock_with_key: '🔐',
  card_file_box: '🗃️', file_cabinet: '🗄️', wastebasket: '🗑️',
  hammer_and_pick: '⚒️', dagger: '🗡️', skull_and_crossbones: '☠️', bow_and_arrow: '🏹',
  rosette: '🏵️', reminder_ribbon: '🎗️', admission_tickets: '🎟️', ticket: '🎫',
  balloon: '🎈', confetti_ball: '🎊', party_popper: '🎉', ribbons: '🎀',
  dancing_women: '💃', dancer: '💃', man_dancing: '🕺',
  juggling_person: '🤹', carousel_horse: '🎠', ferris_wheel: '🎡', roller_coaster: '🎢',
  fishing_pole_and_fish: '🎣', satellite: '🛰️', syringe: '💉', pill: '💊',
  bandage: '🩹', drop_of_blood: '🩸', dna: '🧬', microbe: '🦠', atom_symbol: '⚛️', abacus: '🧮',
  test_tube: '🧪', petri_dish: '🧫', magnifying_glass_tilted_left: '🔍', hole: '🕳️',
  telescope: '🔭', satellite_antenna: '📡', candle: '🕯️', flashlight: '🔦',
  red_lantern: '🏮', diya_lamp: '🪔', prayer_beads: '📿',
  coin: '🪙', yen_banknote: '💴', dollar_banknote: '💵', pound_banknote: '💷', euro_banknote: '💶', money_bag: '💰',
  credit_card: '💳', receipt: '🧾', chart: '💹', chart_increasing: '📈', chart_decreasing: '📉',
  seat: '💺', armchair: '🪑', couch_and_lamp: '🛋️', bed: '🛏️', sleeping_accommodation: '🛌',
  place_of_worship: '🛐', wedding: '💒', japanese_castle: '🏯', european_castle: '🏰',
  stadium: '🏟️', framed_picture: '🖼️', artist_palette: '🎨',
  thread: '🧵', yarn: '🧶', shopping_cart: '🛒', shopping_trolley: '🛒',
  fire_extinguisher: '🧯', restroom: '🚻', baby_symbol: '🚼', water_closet: '🚾',
  passport_control: '🛂', customs: '🛃', baggage_claim: '🛄', left_luggage: '🛅',
  wheelchair: '♿', no_entry_sign: '🚫', no_bicycles: '🚳', smoking: '🚬',
  no_smoking: '🚭', put_litter_in_its_place: '🚮', do_not_litter: '🚯',
  potable_water: '🚰', non_potable_water: '🚱', no_mobile_phones: '📵',
  underage: '🔞', radioactive: '☢️', biohazard: '☣️',
  arrow_up: '⬆️', arrow_down: '⬇️', arrow_left: '⬅️', arrow_right: '➡️',
  up_left_arrow: '↖️', up_right_arrow: '↗️', down_left_arrow: '↙️', down_right_arrow: '↘️',
  left_right_arrow: '↔️', up_down_arrow: '↕️', leftwards_arrow_with_hook: '↩️', arrow_right_hook: '↪️',
  star2: '🌟', hourglass: '⌛', hourglass_flowing_sand: '⏳',
  alarm_clock: '⏰', stopwatch: '⏱️', timer: '⏲️', clock12: '🕛',
  white_flower: '💮', Japanese_acceptable_button: '🉑', Japanese_application_button: '🈸',
  Japanese_bargain_button: '🉐', Congratulations_button: '㊗️', Japanese_discount_button: '🈂️',
  Japanese_free_of_charge_button: '🈚', Japanese_monthly_amount_button: '🈷️',
  Japanese_no_vacancy_button: '🈵', Japanese_open_for_business_button: '🈺',
  Japanese_passport_button: '🛂', Japanese_prohibited_button: '🈲', Japanese_reserved_button: '🈯',
  Japanese_secret_button: '㊙️', Japanese_service_cycle_button: '🈂️', Japanese_symbol_for_beginner: '🆕',
  flag_black: '🏴', flag_white: '🏳️', rainbow_flag: '🏳️‍🌈', pirate_flag: '🏴‍☠️',
  flag_af: '🇦🇫', flag_al: '🇦🇱', flag_dz: '🇩🇿', flag_ad: '🇦🇩', flag_ao: '🇦🇴',
  flag_ai: '🇦🇮', flag_aq: '🇦🇶', flag_ag: '🇦🇬', flag_ar: '🇦🇷', flag_am: '🇦🇲',
  flag_aw: '🇦🇼', flag_au: '🇦🇺', flag_at: '🇦🇹', flag_az: '🇦🇿', flag_bs: '🇧🇸',
  flag_bh: '🇧🇭', flag_bd: '🇧🇩', flag_bb: '🇧🇧', flag_by: '🇧🇾', flag_be: '🇧🇪',
  flag_bz: '🇧🇿', flag_bj: '🇧🇯', flag_bm: '🇧🇲', flag_bn: '🇧🇳', flag_bo: '🇧🇴',
  flag_ba: '🇧🇦', flag_bw: '🇧🇼', flag_br: '🇧🇷', flag_bg: '🇧🇬',
  flag_bf: '🇧🇫', flag_bi: '🇧🇮', flag_kh: '🇰🇭', flag_cm: '🇨🇲', flag_ca: '🇨🇦',
  flag_cv: '🇨🇻', flag_ky: '🇰🇾', flag_cf: '🇨🇫', flag_td: '🇹🇩', flag_cl: '🇨🇱',
  flag_cn: '🇨🇳', flag_co: '🇨🇴', flag_km: '🇰🇲', flag_cg: '🇨🇬', flag_cd: '🇨🇩',
  flag_cr: '🇨🇷', flag_ci: '🇨🇮', flag_hr: '🇭🇷', flag_cu: '🇨🇺', flag_cy: '🇨🇾',
  flag_cz: '🇨🇿', flag_dk: '🇩🇰', flag_dj: '🇩🇯', flag_dm: '🇩🇲', flag_do: '🇩🇴',
  flag_ec: '🇪🇨', flag_eg: '🇪🇬', flag_sv: '🇸🇻', flag_gq: '🇬🇶', flag_er: '🇪🇷',
  flag_ee: '🇪🇪', flag_et: '🇪🇹', flag_eu: '🇪🇺', flag_fk: '🇫🇰', flag_fj: '🇫🇯',
  flag_fi: '🇫🇮', flag_fr: '🇫🇷', flag_ga: '🇬🇦', flag_gm: '🇬🇲', flag_ge: '🇬🇪',
  flag_gf: '🇬🇫', flag_gh: '🇬🇭', flag_gi: '🇬🇮', flag_gr: '🇬🇷', flag_gl: '🇬🇱',
  flag_gd: '🇬🇩', flag_gp: '🇬🇵', flag_gu: '🇬🇺', flag_gt: '🇬🇹', flag_gg: '🇬🇬',
  flag_gn: '🇬🇳', flag_gw: '🇬🇼', flag_gy: '🇬🇾', flag_ht: '🇭🇹', flag_hn: '🇭🇳',
  flag_hk: '🇭🇰', flag_hu: '🇭🇺', flag_is: '🇮🇸', flag_in: '🇮🇳', flag_id: '🇮🇩',
  flag_ir: '🇮🇷', flag_iq: '🇮🇶', flag_ie: '🇮🇪', flag_im: '🇮🇲', flag_il: '🇮🇱',
  flag_it: '🇮🇹', flag_jm: '🇯🇲', flag_je: '🇯🇪', flag_jp: '🇯🇵', flag_jo: '🇯🇴',
  flag_kz: '🇰🇿', flag_ke: '🇰🇪', flag_ki: '🇰🇮', flag_kp: '🇰🇵', flag_kr: '🇰🇷',
  flag_kw: '🇰🇼', flag_kg: '🇰🇬', flag_la: '🇱🇦', flag_lv: '🇱🇻', flag_lb: '🇱🇧',
  flag_ls: '🇱🇸', flag_lr: '🇱🇷', flag_ly: '🇱🇾', flag_li: '🇱🇮', flag_lt: '🇱🇹',
  flag_lu: '🇱🇺', flag_mo: '🇲🇴', flag_mk: '🇲🇰', flag_mg: '🇲🇬', flag_mw: '🇲🇼',
  flag_my: '🇲🇾', flag_mv: '🇲🇻', flag_ml: '🇲🇱', flag_mt: '🇲🇹', flag_mh: '🇲🇭',
  flag_mq: '🇲🇶', flag_mr: '🇲🇷', flag_mu: '🇲🇺', flag_yt: '🇾🇹', flag_mx: '🇲🇽',
  flag_fm: '🇫🇲', flag_md: '🇲🇩', flag_mc: '🇲🇨', flag_mn: '🇲🇳', flag_me: '🇲🇪',
  flag_ms: '🇲🇸', flag_ma: '🇲🇦', flag_mz: '🇲🇿', flag_mm: '🇲🇲', flag_na: '🇳🇦',
  flag_nr: '🇳🇷', flag_np: '🇳🇵', flag_nl: '🇳🇱', flag_nc: '🇳🇨', flag_nz: '🇳🇿',
  flag_ni: '🇳🇮', flag_ne: '🇳🇪', flag_ng: '🇳🇬', flag_nu: '🇳🇺', flag_nf: '🇳🇫',
  flag_mp: '🇲🇵', flag_no: '🇳🇴', flag_om: '🇴🇲', flag_pk: '🇵🇰', flag_pw: '🇵🇼',
  flag_ps: '🇵🇸', flag_pa: '🇵🇦', flag_pg: '🇵🇬', flag_py: '🇵🇾', flag_pe: '🇵🇪',
  flag_ph: '🇵🇭', flag_pl: '🇵🇱', flag_pt: '🇵🇹', flag_pr: '🇵🇷', flag_qa: '🇶🇦',
  flag_re: '🇷🇪', flag_ro: '🇷🇴', flag_ru: '🇷🇺', flag_rw: '🇷🇼', flag_sh: '🇸🇭',
  flag_kn: '🇰🇳', flag_lc: '🇱🇨', flag_pm: '🇵🇲', flag_vc: '🇻🇨', flag_ws: '🇼🇸',
  flag_sm: '🇸🇲', flag_st: '🇸🇹', flag_sa: '🇸🇦', flag_sn: '🇸🇳', flag_rs: '🇷🇸',
  flag_sc: '🇸🇨', flag_sl: '🇸🇱', flag_sg: '🇸🇬', flag_sk: '🇸🇰', flag_si: '🇸🇮',
  flag_sb: '🇸🇧', flag_so: '🇸🇴', flag_za: '🇿🇦', flag_es: '🇪🇸', flag_lk: '🇱🇰',
  flag_sd: '🇸🇩', flag_sr: '🇸🇷', flag_sz: '🇸🇿', flag_se: '🇸🇪', flag_ch: '🇨🇭',
  flag_sy: '🇸🇾', flag_tw: '🇹🇼', flag_tj: '🇹🇯', flag_tz: '🇹🇿', flag_th: '🇹🇭',
  flag_tl: '🇹🇱', flag_tg: '🇹🇬', flag_to: '🇹🇴', flag_tt: '🇹🇹', flag_tn: '🇹🇳',
  flag_tr: '🇹🇷', flag_tm: '🇹🇲', flag_tv: '🇹🇻', flag_ug: '🇺🇬', flag_ua: '🇺🇦',
  flag_ae: '🇦🇪', flag_gb: '🇬🇧', flag_us: '🇺🇸', flag_uy: '🇺🇾', flag_uz: '🇺🇿',
  flag_vu: '🇻🇺', flag_va: '🇻🇦', flag_ve: '🇻🇪', flag_vn: '🇻🇳', flag_wf: '🇼🇫',
  flag_eh: '🇪🇭', flag_ye: '🇾🇪', flag_zm: '🇿🇲', flag_zw: '🇿🇼',
}

marked.use({
  gfm: true,
  breaks: true
})

marked.use(markedEmoji({
  emojis: GITHUB_EMOJI_MAP,
  renderer: (token) => token.emoji
}))

export function parseMarkdownToHTML(markdown: string): string {
  if (!markdown) return ''
  try {
    return marked.parse(markdown) as string
  } catch {
    return markdown
  }
}
